### ISSUE TITLE
Lego Mindstorms download recipe broken

### ISSUE THREAD

**Issue by aysiu** [autopkg/aysiu-recipes#11]
They changed up once again how the download works, and this time it's calling via API instead of actual searchable download link.

Not sure if it's worth a workaround to fix, since it's been the same version for a long time... with just the download method changing.

**Comment by joncohen** [comment]
looks like they may be back to a link - and it is https:
https://le-www-live-s.legocdn.com/downloads/LME-EV3/LME-EV3_Full-setup_1.3.2_en-GB_OSX.dmg

Testing today with an override in Autopkg to confirm.

**Comment by aysiu** [comment]
Thanks, @joncohen, especially if you have a pull request.

**Comment by aysiu** [comment]
Fixed to use the API. Unfortunately, they don't advertise the version any more...
