### ISSUE TITLE
Respondus Lockdown Download Improvements

### ISSUE THREAD

**Issue by foigus** [autopkg/aysiu-recipes#12]
Two ideas:

1) Make the AutoPkg user's life easier by making them only override the customer ID
2) Use `StopProcessingIf` to check if the ID _hasn't_ been overridden

https://github.com/autopkg/aysiu-recipes/blob/master/LockDownBrowser/LockDownBrowser.download.recipe#L14-L15

**Comment by aysiu** [comment]
Thanks, @foigus. Not sure I really understand `NSPredicate-style comparison against an environment key. See http://developer.apple.com/library/mac/#documentation/Cocoa/Conceptual/Predicates/Articles/pSyntax.html` and how that would apply to a local AutoPkg variable. Is there an example you can link me to? The only examples I could find didn't seem to directly apply here. Example:
https://github.com/autopkg/nmcspadden-recipes/blob/master/AppStoreApp/AppStoreApp.munki.recipe#L35-L43

**Comment by foigus** [comment]
This is an example of `StopProcessingIf`:

https://github.com/autopkg/foigus-recipes/blob/19aa8d332d7bbc3a19d0c2e81f6a61b248e66e8f/Ecamm/CallRecorderforSkype.download.recipe#L31-L48

**Comment by aysiu** [comment]
Thanks, @foigus. That example was super helpful.
https://github.com/autopkg/aysiu-recipes/commit/1eba2cace74f124bbbe26418412dff0b4f788ec2
