### ISSUE TITLE
Scratch URLDownloader failing

### ISSUE THREAD

**Issue by eshirk** [autopkg/aysiu-recipes#18]
Hi there--I'm getting the following error with the Scratch recipe:

Error in local.munki.Scratch: Processor: URLDownloader: Error: Curl failure: The requested URL returned error: 400  (exit code 22)

The URLTextSearcher appears to work properly, as loading https://scratch.mit.edu/scratchr2/static/sa/Scratch-461.dmg manually results in a download. Guessing it's the NAME value, Scratch vs. Scratch 2?

Thanks for providing this recipe!

**Comment by macmule** [comment]
@eshirk looks ok now.. maybe an issue with the XML for a little?

**Comment by eshirk** [comment]
@macmule looks to be the case--thanks for the update!

**Comment by Daz-wallace** [comment]
Pull request with a fix submitted as #19
