### ISSUE TITLE
Burn download failing with Error: No matched files

### ISSUE THREAD

**Issue by Daz-wallace** [autopkg/aysiu-recipes#22]
Getting an error on com.github.aysiu.download.Burn from the SourceForgeURLProvider of "No matched files"

I'm going to take a look but I might not be able to fix it for a pull request

**Comment by Daz-wallace** [comment]
Pull request #23

**Comment by macmule** [comment]
bump!

**Comment by Daz-wallace** [comment]
Bumpy McBumpFace 😊
