### ISSUE TITLE
URLTextSearcher issue seems to have returned

### ISSUE THREAD

**Issue by beatlemike** [autopkg/aysiu-recipes#27]
Suddenly looks like Respondus changed something again

"Processor: URLTextSearcher: Error: No match found on URL: https://www.respondus.com/lockdown/download7.php?id=mine"

**Comment by aysiu** [comment]
I don't work at a school any more, so this is a bit tough for me to troubleshoot. Do you want to figure out the download link and the make a pull request?

**Comment by beatlemike** [comment]
I'm not sure if its the link, I know it it changed to 
https://download.respondus.com/lockdown/download7.php?id=

But if I create an override with it, it still can't find the version. Maybe it's the searcg pattern for URLTextSearcher?

**Comment by aysiu** [comment]
It _changed_ to that? That's what it currently is:
https://github.com/autopkg/aysiu-recipes/blob/master/LockDownBrowser/LockDownBrowser.download.recipe#L17

Again, I don't work at a school now, so I don't have a LockDownBrowser download to test with. If you can get it working outside of AutoPkg (i.e., just an actual download link), that'll give you a sense of what the URL should look like, and you can make a pull request here.

**Comment by aysiu** [comment]
@beatlemike , someone on the MacAdmins Slack suggested this might be the new URL for non-lab: `https://download.respondus.com/lockdown/download.php?id=` can you try that, and see if it works for you?

**Comment by beatlemike** [comment]
Found it I think, darn button:

https://download.respondus.com/lockdown/download7.php?id=INSTITUTION_ID&ostype=2

**Comment by aysiu** [comment]
I'm getting conflicting messages here. That said, all of those variables are inputs, so you can always change it in the recipe override to verify it works. If it works, make a PR, so we can change it in the original recipe.
https://github.com/autopkg/aysiu-recipes/blob/master/LockDownBrowser/LockDownBrowser.download.recipe#L16-L19

**Comment by beatlemike** [comment]
The link you just sent me is the same link I initially gave you, tried that one, didn't work as web download or as an override.

This link:
https://download.respondus.com/lockdown/download7.php?id=INSTITUTION_ID&ostype=2

Works as a web download, but I haven't got it to download yet in an override. 

I'm afraid I don't know how to do a pull request quite yet or I will if I can get this working in an override.

**Comment by beatlemike** [comment]
and I totally appreciate you putting up with my ignorance right now. I really do.

**Comment by aysiu** [comment]
Someone else has volunteered to take on this set of recipes. Once those are up and running in another repo, I'll put deprecation warnings on my recipes, and probably just make these stubs with the new recipes as parent recipes.

**Comment by beatlemike** [comment]
Awesome! Thanks for all you have done both now and in the past with this.
