### ISSUE TITLE
MalwarebytesAntiMalware - Could not find parent recipe

### ISSUE THREAD

**Issue by vmgstudio520** [autopkg/aysiu-recipes#8]
Could not find parent recipe for com.github.aysiu.munki.MalwarebytesAntiMalware
No valid recipe found for com.github.aysiu.munki.MalwarebytesAntiMalware

**Comment by aysiu** [comment]
That's weird. I just ran it and didn't get that error. Can you post your own output of `autopkg run -v MalwarebytesAntiMalware.munki`?

```
autopkg run -v MalwarebytesAntiMalware.munki
Processing MalwarebytesAntiMalware.munki...
SparkleUpdateInfoProvider
SparkleUpdateInfoProvider: Version retrieved from appcast: 1.2.6
SparkleUpdateInfoProvider: Found URL https://data-cdn.mbamupdates.com/v1/mbam-mac/data/mbam-mac-1.2.6.zip
URLDownloader
URLDownloader: Item at URL is unchanged.
URLDownloader: Using existing /Users/username/Library/AutoPkg/Cache/com.github.aysiu.munki.MalwarebytesAntiMalware/downloads/mbam-mac-1.2.6.zip
EndOfCheckPhase
Unarchiver
Unarchiver: Guessed archive format 'zip' from filename mbam-mac-1.2.6.zip
Unarchiver: Unarchived /Users/username/Library/AutoPkg/Cache/com.github.aysiu.munki.MalwarebytesAntiMalware/downloads/mbam-mac-1.2.6.zip to /Users/username/Library/AutoPkg/Cache/com.github.aysiu.munki.MalwarebytesAntiMalware/Malwarebytes
CodeSignatureVerifier
CodeSignatureVerifier: Verifying application bundle signature...
CodeSignatureVerifier: /Users/username/Library/AutoPkg/Cache/com.github.aysiu.munki.MalwarebytesAntiMalware/Malwarebytes/Malwarebytes Anti-Malware.app: valid on disk
CodeSignatureVerifier: /Users/username/Library/AutoPkg/Cache/com.github.aysiu.munki.MalwarebytesAntiMalware/Malwarebytes/Malwarebytes Anti-Malware.app: satisfies its Designated Requirement
CodeSignatureVerifier: /Users/username/Library/AutoPkg/Cache/com.github.aysiu.munki.MalwarebytesAntiMalware/Malwarebytes/Malwarebytes Anti-Malware.app: explicit requirement satisfied
CodeSignatureVerifier: Signature is valid
Unarchiver
Unarchiver: Guessed archive format 'zip' from filename mbam-mac-1.2.6.zip
Unarchiver: Unarchived /Users/username/Library/AutoPkg/Cache/com.github.aysiu.munki.MalwarebytesAntiMalware/downloads/mbam-mac-1.2.6.zip to /Users/username/Library/AutoPkg/Cache/com.github.aysiu.munki.MalwarebytesAntiMalware/Malwarebytes
DmgCreator
DmgCreator: Created dmg from /Users/username/Library/AutoPkg/Cache/com.github.aysiu.munki.MalwarebytesAntiMalware/Malwarebytes at /Users/username/Library/AutoPkg/Cache/com.github.aysiu.munki.MalwarebytesAntiMalware/Malwarebytes.dmg
MunkiImporter
MunkiImporter: Item Malwarebytes.dmg already exists in the munki repo as pkgs/apps/Malwarebytes-1.2.6.dmg.
Receipt written to /Users/username/Library/AutoPkg/Cache/com.github.aysiu.munki.MalwarebytesAntiMalware/receipts/MalwarebytesAntiMalware-receipt-20170208-082434.plist
```

**Comment by vmgstudio520** [comment]
autopkg run -v MalwarebytesAntiMalware.munki
Didn't find a recipe for com.github.rtrouton.download.MalwarebytesAntiMalware.
Search GitHub AutoPkg repos for a com.github.rtrouton.download.MalwarebytesAntiMalware recipe? [y/n]: y

Name                                        Repo                 Path                                    
----                                        ----                 ----                                    
MalwarebytesAntiMalware.munki.recipe        aysiu-recipes        MalwarebytesAntiMalware/MalwarebytesAntiMalware.munki.recipe
MalwarebytesAntiMalware.jss.recipe          rtrouton-recipes     JSS/MalwarebytesAntiMalware.jss.recipe  
MalwarebytesAntiMalware.pkg.recipe          rtrouton-recipes     MalwarebytesAntiMalware/MalwarebytesAntiMalware.pkg.recipe
MalwarebytesAntiMalware.download.recipe     rtrouton-recipes     MalwarebytesAntiMalware/MalwarebytesAntiMalware.download.recipe

To add a new recipe repo, use 'autopkg repo-add <repo name>'
Could not find parent recipe for MalwarebytesAntiMalware.munki

Nothing downloaded, packaged or imported.

**Comment by aysiu** [comment]
Try `autopkg repo-add rtrouton-recipes`

And then `autopkg run -v MalwarebytesAntiMalware.munki`

**Comment by vmgstudio520** [comment]
Worked that time! Thanks for your help, really appreciate it. :)
